channels:
  - name: sig-security
  - name: sig-security-docs
  - name: sig-security-tooling
  - name: sig-security-assessments
  - name: sig-security-assess-etcd
  # Retired channels noted for future reference
  - name: sig-security-assess-vsphere-csi-driver
    archived: true
  - name: sig-security-assess-capi
    arhcived: true
